% Revision history
% --------------------------------------------------
% 
%      October 2016 Christian Power (power@na.uni-tuebingen.de)
%      September 2016 Christian Power (power@na.uni-tuebingen.de)
%       Originally written by Christian Power
%            (power22c@gmail.com) 2015
%
%  Standard packages for my LaTeX beamer slides.
%  Copyright (c) 2016 Christian Power.  All rights reserved.
% ----------------------------------------------------------------------

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{capgBeamer}[2016/10/03 v0.0.1 Slides]

\LoadClass[xcolor={usenames,dvipsnames}]{beamer}
\RequirePackage[T1]{fontenc}
\RequirePackage[utf8]{inputenc}
\RequirePackage{amsmath, mathtools}
\RequirePackage{amssymb, mathrsfs, dsfont}
\RequirePackage{amsthm}
\RequirePackage{graphicx, graphics, color}
\RequirePackage{microtype}
\RequirePackage{lmodern}
\RequirePackage{exscale}
\RequirePackage{booktabs}
\RequirePackage{xparse, xifthen}
\RequirePackage{tikz}
\usetikzlibrary{arrows,decorations.pathmorphing,backgrounds,positioning,fit,petri}
\RequirePackage{tcolorbox}
\RequirePackage{listings}
\RequirePackage{lstMatlabJulia}
\RequirePackage{capg_slides}
