%  Revision history
%  --------------------------------------------------
%
%       Revised by Christian Power October 2016
%       Originally written by Christian Power
%            (power22c@gmail.com) October 2016
%
%  This class is for quick notes.
%  Copyright (c) 2016 Christian Power.  All rights reserved.
% ----------------------------------------------------------------------

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{note}[2016/10/13 v0.0.0 note class]

\LoadClass[a5paper, DIV=calc]{scrartcl}
\RequirePackage[colorlinks=true,pdfpagelabels]{hyperref}
\hypersetup{linkcolor=blue, citecolor=blue}
\RequirePackage{enumitem}
\RequirePackage{stdPack}
\RequirePackage{hyph}
\RequirePackage{capgPalatino}
\RequirePackage[mathpazo]{flexisym}
\RequirePackage{breqn}
\RequirePackage{capgThm}
\RequirePackage{mathMacr}

\recalctypearea
\RequirePackage[ngerman, english]{babel}
