%  Revision history
%  --------------------------------------------------
%
%       Revised by Christian Power October 2016
%       Originally written by Christian Power
%            (power22c@gmail.com) October 2016
%
%  This class is for quick notes.
%  Copyright (c) 2016 Christian Power.  All rights reserved.
% ----------------------------------------------------------------------

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{note}[2017/07/25 v0.0.2 note class]

\LoadClass[a5paper, DIV=calc]{scrartcl}
\RequirePackage[headsepline=.5pt]{scrlayer-scrpage}
\RequirePackage[colorlinks=true,pdfpagelabels]{hyperref}
\RequirePackage[titles]{tocloft}
\hypersetup{linkcolor=blue, citecolor=blue}
\RequirePackage{enumitem}
\RequirePackage{stdPack}
\RequirePackage{hyph}
\RequirePackage{capgPalatino}
\RequirePackage[mathpazo]{flexisym}
\RequirePackage{breqn}
\RequirePackage{capgThm}
\RequirePackage{mathMacr}

\RequirePackage{epigraph}
\RequirePackage{newfloat}
\RequirePackage{caption}
\setlength\epigraphwidth{8cm}
\setlength\epigraphrule{0pt}
\recalctypearea
% \RequirePackage[ngerman, english]{babel}
\renewcommand\labelitemi{\(\bullet\)}

