%  Revision history
%  --------------------------------------------------
%
%       Revised by Christian Power October 2016
%       Originally written by Christian Power
%            (power22c@gmail.com) 25.09.2016
%
%  Style file to create the presentation for the defense
%  of my thesis.
%  Copyright (c) 2016 Christian Power.  All rights reserved.
% ----------------------------------------------------------------------

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{tuebingenDissDefense}[2017/06/05 v0.0 Thesis slide class]

\LoadClass{capgBeamer}
\RequirePackage{hyph}
% \RequirePackage[mathpazo]{flexisym}
\RequirePackage{breqn}
\RequirePackage{slideThm}
\RequirePackage{mathMacr}
\RequirePackage[ngerman, english]{babel}

% \RequirePackage[colorlinks=true,pdfpagelabels]{hyperref}
% \hypersetup{linkcolor=black, citecolor=black}

% \renewcommand*\labelitemi{\(\bullet\)}
