%  Revision history
%  --------------------------------------------------
%
%       Originally written by Christian Power
%            (power22c@gmail.com) 25.09.2016
%
%  Thesis style file for the University of Tübingen in DIN A5 for the
%  Mathematisch Naturwissenschaftliche faculty.
%  Copyright (c) 2016 Christian Power.  All rights reserved.
% ----------------------------------------------------------------------

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{tuebingenDiss}[2016/09/25 v0.0.0 Thesis class]

\LoadClass[a5paper, twoside, BCOR=1cm, DIV=calc, pagesize=auto]{scrreprt}
% \KOMAoptions{DIV=last}
\RequirePackage{nonMath}
\RequirePackage{myMathPack}
\RequirePackage{myPalatino}
\RequirePackage[mathpazo]{flexisym}
\RequirePackage{breqn}
\RequirePackage{thesisThm}
\RequirePackage{tuebingenTitle} 
\RequirePackage{thesisChap} 
\RequirePackage{myMathSymb}
\hypersetup{linkcolor=blue, citecolor=blue}
